- name: Create install directory
  file:
    path: "{{ install_directory }}/sonarr"
    state: directory
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/sonarr/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  become: true

- name: Start docker container
  community.docker.docker_compose:
    project_src: "{{ install_directory }}/sonarr"
    pull: true
    remove_orphans: yes
