- name: Create service user
  user:
    name: git
    password_lock: yes
    generate_ssh_key: yes
    ssh_key_comment: Gitea Host Key
  register: service_user
  become: true

- name: Add user git's ssh key to its own authorized_key file
  ansible.posix.authorized_key:
    user: git
    key: "{{ service_user.ssh_public_key }}"
  become: true

- name: Install SSH shim script
  copy:
    src: ssh_shim.sh
    dest: /usr/local/bin/gitea
    owner: "{{ service_user.uid }}"
    group: "{{ service_user.group }}"
    mode: 711
  become: true

- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  become: true

- name: Start docker container
  community.docker.docker_compose:
    project_src: "{{ install_directory }}/{{ role_name }}"
    pull: true
    remove_orphans: yes
