version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  tautulli:
    container_name: "tautulli"
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - "PUID={{ service_user.uid }}"
      - "PGID={{ service_user.uid }}"
      - "TZ={{ timezone }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/config"
    labels:
      traefik.enable: true
      traefik.http.routers.tautulli.rule: "Host(`tautulli.local.{{ personal_domain }}`)"
      traefik.http.routers.tautulli.middlewares: ip-whitelist@file
