version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    networks:
      - traefik
    user: "{{ primary_uid }}:{{ primary_gid }}"
    environment:
      - TZ={{ timezone }}
    command:
      - serve
    volumes:
      - "{{ data_dir }}/ntfy:/etc/ntfy"
      - /var/cache/ntfy:/var/cache/ntfy
    labels:
      traefik.enable: true
      traefik.http.routers.ntfy.rule: "Host(`push.{{ personal_domain }}`)"
      traefik.http.routers.ntfy.middlewares: lan-whitelist@file
