- name: Create media group
  ansible.builtin.group:
    name: media
    gid: 997
    system: true
    state: present

- name: Set media directory permissions
  ansible.builtin.file:
    path: "{{ media_storage_mnt }}/data"
    state: directory
    owner: "{{ primary_gid }}"
    group: media
    mode: 0775
    recurse: yes
  become: true
