- name: Create media group
  ansible.builtin.group:
    name: media
    gid: 997
    system: true
    state: present

- name: Set media directory permissions
  ansible.builtin.file:
    path: "{{ media_storage_mnt }}/data"
    group: media
    mode: "a=,a+rX,u+w,g+w"
    recurse: yes
  become: true
