version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    networks:
      - traefik
      - docker-socket-proxy
    environment:
      - "PUID={{ service_user.uid }}"
      - "PGID={{ service_user.uid }}"
      - "TZ={{ timezone }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/app/config"
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: "Host(`homepage.local.{{ personal_domain }}`)"
      traefik.http.routers.homepage.middlewares: lan-whitelist@file
