version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  {{ role_name }}:
    container_name: "{{ role_name }}"
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - "PUID={{ service_user.uid }}"
      - "PGID={{ service_user.uid }}"
      - "TZ={{ timezone }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/config"
    labels:
      traefik.enable: true
      traefik.http.routers.{{ role_name }}.rule: "Host(`requests.{{ personal_domain }}`)"
