version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  minetest:
    container_name: minetest
    image: lscr.io/linuxserver/minetest:latest
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - "PUID={{ service_user.uid }}"
      - "PGID={{ service_user.uid }}"
      - "TZ={{ timezone }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/config/.minetest"
    labels:
      traefik.enable: true
      traefik.http.routers.minetest.rule: "Host(`minetest.{{ personal_domain }}`)"
