- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  become: true

- name: Copy settings file to destionation
  template:
    src: settings.yml
    dest: "{{ data_dir }}/{{ role_name }}/settings.yml"
    owner: "{{ docker_user }}"
  become: true
  notify: restart searxng

- name: Start docker container
  community.docker.docker_compose:
    project_src: "{{ install_directory }}/{{ role_name }}"
    pull: true
    remove_orphans: yes
