version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID={{ primary_uid }}
      - PGID={{ media_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ data_dir }}/qbittorrent:/config"
      - "{{ media_storage_mnt }}/data/torrents:/downloads"
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: "Host(`qbittorrent.local.{{ personal_domain }}`)"
      traefik.http.routers.qbittorrent.middlewares: lan-whitelist@file
