- name: Create service user
  user:
    name: "{{ role_name }}"
    system: true
  register: service_user
  become: true

- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create config directory
  file:
    path: "{{ data_dir }}/{{ role_name }}"
    state: directory
    owner: "{{ service_user.uid }}"
    group: "{{ media_gid }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Copy config file to config directory
  template:
    src: slskd.yml
    dest: "{{ data_dir }}/{{ role_name }}"
    owner: "{{ service_user.uid }}"
  become: true
  notify: restart service

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  become: true

- name: Start docker container
  community.docker.docker_compose:
    project_src: "{{ install_directory }}/{{ role_name }}"
    pull: true
    remove_orphans: yes
