version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    restart: unless-stopped
    networks:
      - default
    environment:
      MEILI_MASTER_KEY: "{{ meili_master_key }}"
      MEILI_ENV: production
    volumes:
      - "{{ data_dir }}/barassistant/meilisearch:/meili_data"

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    environment:
      ALLOW_EMPTY_PASSWORD: "True"

  bar-assistant:
    image: barassistant/server:latest
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - meilisearch
      - redis
    environment:
      APP_URL: "{{ base_url }}/bar"
      LOG_CHANNEL: stderr
      MEILISEARCH_KEY: "{{ meili_master_key }}"
      MEILISEARCH_HOST: http://meilisearch:7700
      REDIS_HOST: redis
      ALLOW_REGISTRATION: "True"
    volumes:
      - "{{ data_dir }}/barassistant/barassistant:/var/www/cocktails/storage/bar-assistant"

  salt-rim:
    image: barassistant/salt-rim:latest
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - bar-assistant
    environment:
      API_URL: "{{ base_url }}/bar"
      MEILISEARCH_URL: "{{ base_url }}/search"
      BAR_NAME: "Cocktails"
      DESCRIPTION: Why is the rum always gone?
      DEFAULT_LOCALE: "en-US"

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - traefik
      - default
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    labels:
      traefik.enable: true
      traefik.http.routers.barassistant.rule: "Host(`cocktails.{{ personal_domain }}`)"
      traefik.http.services.barassistant.loadbalancer.server.port: 3000
