version: "3"

networks:
  traefik:
    external: true

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - traefik
    ports:
      - 8888:8888 # HTTP Proxy
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_TYPE: wireguard
      VPN_SERVICE_PROVIDER: custom
      WIREGUARD_PRIVATE_KEY: "{{ wireguard_private_key }}"
      WIREGUARD_PUBLIC_KEY: "1N3x3+Ojc8jONodU0eBnLth3qcmrdlrNK9tkUnVGHT4="
      WIREGUARD_ADDRESSES: "10.13.128.85/24"
      VPN_ENDPOINT_IP: "67.213.221.27"
      VPN_ENDPOINT_PORT: "1443"
      FIREWALL_VPN_INPUT_PORTS: "42382"
      DOT: "off"
      DNS_ADDRESS: "10.8.0.1"
      TZ: "{{ timezone }}"
      HTTPPROXY: "on"
      HTTPPROXY_USER: httpproxy
      HTTPPROXY_PASSWORD: httpproxy
