entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: :443
    http:
      middlewares:
        - secure-headers@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: "{{ personal_domain }}"
          - sans: "*.{{ personal_domain }}"
          - main: "local.{{ personal_domain }}"
          - sans: "*.local.{{ personal_domain }}"
  
  traefik:
    address: :8080

api:
  dashboard: true
  debug: false

certificatesResolvers:
  letsencrypt:
    acme:
      # Staging server
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory

      # Production server
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: "{{ letsencrypt_email }}"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: porkbun
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"

serversTransport:
  insecureSkipVerify: true

tls:
  options:
    default:
      minVersion: VersionTLS12

providers:
  docker:
    endpoint: tcp://docker_socket_proxy:2375
    exposedByDefault: false
    network: traefik
  file:
    directory: /etc/traefik/conf
    watch: true
