- name: Install docker
  ansible.builtin.package:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ primary_user }}"
    groups: docker
    append: true
  become: true

- name: Start Docker daemon at boot
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started
  become: true

- name: Install docker compose
  ansible.builtin.package:
    name: docker-compose
    state: present
  become: true
