http:
  routers:
    router-jellyfin:
      rule: "Host(`jellyfin.{{ personal_domain }}`)"
      service: service-jellyfin

  services:
    service-jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.0.30:8096
