version: "{{ docker_compose_version }}"

services:
  slskd:
    container_name: "slskd"
    image: slskd/slskd
    restart: unless-stopped
    network_mode: "container:gluetun"
    user: "{{ service_user.uid }}:{{ media_gid }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/app"
      - "{{ media_storage_mnt }}/data/import/music/soulseek:/downloads"
      - "{{ media_storage_mnt }}/data/media/music:/music:ro"
    labels:
      traefik.enable: true
      traefik.http.routers.slskd.rule: "Host(`soulseek.local.{{ personal_domain }}`)"
      traefik.http.routers.slskd.middlewares: lan-whitelist@file
      traefik.http.services.slskd.loadbalancer.server.port: 5030
