version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  {{ role_name }}:
    container_name: "{{ role_name }}"
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - "PUID={{ service_user.uid }}"
      - "PGID={{ media_gid }}"
      - "TZ={{ timezone }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/config"
      - "{{ media_storage_mnt }}/data:/data"
    labels:
      traefik.enable: true
      traefik.http.routers.{{ role_name }}.rule: "Host(`{{ role_name }}.local.{{ personal_domain }}`)"
      traefik.http.routers.{{ role_name }}.middlewares: lan-whitelist@file
