version: "{{ docker_compose_version }}"

networks:
  traefik:
    external: true

services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:develop
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PUID={{ primary_uid }}
      - PGID={{ media_gid }}
      - TZ={{ timezone }}
    volumes:
      - "{{ data_dir }}/sonarr:/config"
      - "{{ media_storage_mnt }}/data:/data"
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: "Host(`sonarr.local.{{ personal_domain }}`)"
      traefik.http.routers.sonarr.middlewares: lan-whitelist@file
