- hosts: pve
  roles:
    - role: ironicbadger.proxmox_nag_removal
      
- hosts: pve-docker
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users: "{{ primary_user }}"
