- hosts:
  - pve-docker
  roles:
    - role: geerlingguy.ntp
      become: true
      vars:
        - ntp_timezone: "{{ timezone }}"
        - ntp_manage_config: true


- hosts: pve-docker
  roles:
    - role: geerlingguy.docker
      become: true
