- hosts: pve
  roles:
    - pve

- hosts: pve-docker
  roles:
    - pve-docker
    - docker-compose
    - gluetun
    - traefik
    - recyclarr
    - prowlarr
    - sonarr
    - radarr
    - qbittorrent
    - overseerr
    - ntfy
