version: "{{ docker_compose_version }}"

networks:
  starr:
    external: true

services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    restart: unless-stopped
    user: "{{ service_user.uid }}:{{ service_user.uid }}"
    networks:
      - starr
    environment:
      - "TZ={{ timezone }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}:/config"
