- name: Create service user
  user:
    name: "{{ role_name }}"
    groups: "{{ media_group }}"
    append: yes
    system: true
  register: service_user
  become: true

- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  become: true

- name: Install qbitmanage config file
  copy:
    src: qbitmanage/config.yml
    dest: "{{ data_dir }}/qbitmanage/config.yml"
    owner: "{{ service_user.uid }}"
    mode: "{{ docker_compose_file_mask }}"
  notify: restart qbittorrent
  become: true

- name: Create cross-seed config directory
  file:
    path: "{{ data_dir }}/cross-seed"
    state: directory
    owner: "{{ service_user.uid }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install cross-seed config file
  template:
    src: cross-seed/config.js
    dest: "{{ data_dir }}/cross-seed/config.js"
    owner: "{{ service_user.uid }}"
    mode: "{{ docker_compose_file_mask }}"
  notify: restart qbittorrent
  become: true

- name: Start docker containers
  community.docker.docker_compose:
    project_src: "{{ install_directory }}/{{ role_name }}"
    pull: true
    remove_orphans: yes
